### ISSUE TITLE
getting an error  AttributeError: module 'tensorflow' has no attribute 'Dimension' while trying to run style GAN

### ISSUE THREAD

**Issue by deekshantsaxena** [jeffheaton/present#1]
getting an error  AttributeError: module 'tensorflow' has no attribute 'Dimension' while trying to run style GAN

need your help for resolution, was working on google colab following your video

**Comment by deekshantsaxena** [comment]
Requirement already satisfied: tflib in /usr/local/lib/python3.6/dist-packages (0.1.0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-1168089e32b0> in <module>()
     12 import PIL.Image
     13 import dnnlib
---> 14 import dnnlib.tflib as tflib
     15 import config
     16 

2 frames
/content/stylegan/dnnlib/tflib/tfutil.py in <module>()
     32 
     33 
---> 34 def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:
     35     """Convert a Tensorflow shape to a list of ints."""
     36     return [dim.value for dim in shape]

AttributeError: module 'tensorflow' has no attribute 'Dimension'

**Comment by jeffheaton** [comment]
That looks like a version issue between TF and StyleGAN.  You will probably have better luck submitting a StyleGAN issue.
