### ISSUE TITLE
Updated Wikipedia Code

### ISSUE THREAD

**Issue by ToddMorrill** [jeffheaton/present#7]
Hey Jeff - I'm reaching out because I'm working on a project where I needed to download Wikipedia and extract links for an entity linking task. I wanted to share some code that I've been working on, some of which I edited from your repo (e.g. [download_wikipedia.py](https://github.com/ToddMorrill/knowledge-graphs/blob/master/kg/entity_linking/download_wikipedia.py)), some of which I wrote from scratch ([extract_wikipedia.py](https://github.com/ToddMorrill/knowledge-graphs/blob/master/kg/entity_linking/extract_wikipedia.py), etc.). Have a look! I suspect you'll find your beefy CPU machine pinned at 100% utilization. 

Thanks for your videos and code.

**Comment by jeffheaton** [comment]
Thank you, I will have a look soon.  You are right, that code needed some optimization.
