### ISSUE TITLE
Getting error " UnpicklingError: invalid load key, '\x0a'." 

### ISSUE THREAD

**Issue by Vinod95-git** [jeffheaton/present#9]
tried even to download the file and upload to drive still getting same error can you please help me with this.

<img width="667" alt="github" src="https://user-images.githubusercontent.com/78753959/122988141-508ff200-d399-11eb-9f8e-fae1bb267b85.PNG">

**Comment by aliyabannaeva** [comment]
Had the same issue, my pickle file was probably corrupt. Downloading it again solved the issue

**Comment by jeffheaton** [comment]
Which file are you getting this error on?  (I have alot of projects in this repo)
